################################################################################
## Energy CONFIG by Johan71
################################################################################
sensor:
  - platform: template
    sensors:
      solar_benefit:
        friendly_name: "Solar Benefit"
        unit_of_measurement: "Sek/h"
        value_template: >
          {{ states('sensor.solar_to_house')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000
             + states('sensor.solar_to_battery')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000
             + states('sensor.solar_to_grid')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000 }}

      battery_benefit:
        friendly_name: "Battery Benefit"
        unit_of_measurement: "Sek/h"
        value_template: >
          {{ states('sensor.battery_to_grid')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000
             - states('sensor.grid_to_battery')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000
             - states('sensor.solar_to_battery')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000
             + states('sensor.battery_to_house')|float(0) * states('sensor.nordpool_tibber')|float(0)/1000 }}

      battery_solar_benefit:
        friendly_name: "Battery + Solar Benefit"
        unit_of_measurement: "Sek/h"
        value_template: >
          {{ states('sensor.battery_benefit')|float(0) + states('sensor.solar_benefit')|float(0) }}
