#### Start #####################################################################
# Loads default set of integrations. Do not remove.
default_config:
#external_url: !secret external_url
##
# logs:
## API
api:
## EMHASS
notify:
  - platform: file
    name: heating_hours_prediction
    timestamp: false
    filename: /share/heating_prediction.csv
## HA
homeassistant:
  allowlist_external_dirs:
    - "/config"
    - "/share"
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes
#### include ###################################################################
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
device_tracker: !include devicetracker.yaml
shell_command: !include shell_commands.yaml
rest_command: !include rest_command.yaml
mqtt: !include mqtt.yaml
#template: !include forecast.yaml
logger: !include logger.yaml
#### End #######################################################################
