#### Start #####################################################################
# Loads default set of integrations. Do not remove.
default_config:
#external_url: "https://XXXXXXXXXXXXXXXXXX974ogtbmcc89t.ui.nabu.casa"
##
logger:
  default: warn
  # logs:
## EMHASS 
notify:
  - platform: file
    name: heating_hours_prediction
    timestamp: false
    filename: /share/heating_prediction.csv
## HA
homeassistant:
  allowlist_external_dirs:
    - "/config"
    - "/share"
## CUSTOMIZE
#   customize:
    # sensor.compr_cons_hotwat:
    #   state_class: total_increasing
    #   unit_of_measurement: kWh
    #   device_class: energy
## PACKAGES
  packages:
    huawei_solar_data: !include packages/huawei_solar_data.yaml # egen
    elpris_tibber_nordpool: !include packages/elpris_tibber_nordpool.yaml # egen
    lightning: !include packages/lightning.yaml
    emhass: !include packages/emhass.yaml #egen
    emhass_heat: !include packages/emhass_heating.yaml #egen
    predbat: !include packages/predbat.yaml #egen
###
frontend:
  themes: !include_dir_merge_named themes
#### include ###################################################################
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
device_tracker: !include devicetracker.yaml
shell_command: !include shell_commands.yaml
rest_command: !include rest_command.yaml
template: !include forecast.yaml
#### End #######################################################################
