################################################################################
## EMHASS CONFIG by Johan71
################################################################################
# Ta inte bort tänk på ev konsekvenser.
sensor:
  - platform: template
    sensors:
      power_load_novar_loads:
        friendly_name: "Power load no var loads"
        unit_of_measurement: "W"
        device_class: "power"
        unique_id: 43f22bc3-b2b9-4d1c-a555-834b831f31c6
        value_template: >
          {% set powerload = states('sensor.house_consumption_power') | float(default=0) %}
          {% set laddbox_power = states('sensor.go_echarger_265216_nrg_12') | float(default=0) %}
          {% set value = (powerload - laddbox_power) | round(1) %}
          {{ value }}
################################################################################
# END
################################################################################
