################################################################################
## EMHASS CONFIG by Johan71
################################################################################
# Ta inte bort tänk på ev konsekvenser.
sensor:
  - platform: template
    sensors:
      power_load_no_var_loads:
        friendly_name: "Power Load (no Var Loads)"
        unit_of_measurement: "W"
        device_class: "power"
        unique_id: fbfeef21-1aa3-4a54-b781-426f46fef597
        value_template: >
          {% set powerload = states('sensor.house_consumption_power') | float(default=0) %}
          {% set tvatt_power = states('sensor.tvattmaskin_energy_power') | float(default=0) %}
          {% set disk_power = states('sensor.nous_1_energy_power') | float(default=0) %}
          {% set laddbox_power = states('sensor.laddboxforbrukning_power') | float(default=0) %}
          {% set torktumlare_power = states('sensor.torktumlare_energy_power') | float(default=0) %}
          {% set value = (powerload - tvatt_power - disk_power - laddbox_power - torktumlare_power + torktumlare_power) | round(1) %}
          {{ value }}
      # Ta inte bort
      power_load_novar_loads:
        friendly_name: "Power load no var loads"
        unit_of_measurement: "W"
        device_class: "power"
        unique_id: 43f22bc3-b2b9-4d1c-a555-834b831f31c6
        value_template: >
          {% set powerload = states('sensor.house_consumption_power') | float(default=0) %}
          {% set tvatt_power = states('sensor.tvattmaskin_energy_power') | float(default=0) %}
          {% set disk_power = states('sensor.nous_1_energy_power') | float(default=0) %}
          {% set laddbox_power = states('sensor.laddboxforbrukning_power') | float(default=0) %}
          {% set torktumlare_power = states('sensor.torktumlare_energy_power') | float(default=0) %}
          {% set value = (powerload - tvatt_power - disk_power - laddbox_power - torktumlare_power + torktumlare_power) | round(1) %}
          {{ value }}
      # Active timeslots
      active_timeslots_minus_deferrable0_hours:
        friendly_name: "Active Tslots Minus Def0 Hours"
        unit_of_measurement: "hours"
        value_template: >
          {% set active_timeslots = states('sensor.active_timeslots') %}
          {% set p_deferrable0_hours = states('sensor.p_deferrable0_hours') %}
          {% if active_timeslots == 'unavailable' or p_deferrable0_hours == 'unavailable' %}
            0
          {% else %}
            {% set active_timeslots = active_timeslots | int %}
            {% set p_deferrable0_hours = p_deferrable0_hours | int %}
            {% if p_deferrable0_hours == 0 %}
              0
            {% else %}
              {{ active_timeslots - p_deferrable0_hours }}
            {% endif %}
          {% endif %}

      active_timeslots_minus_deferrable1_hours:
        friendly_name: "Active Tslots Minus Def1 Hours"
        unit_of_measurement: "hours"
        value_template: >
          {% set active_timeslots = states('sensor.active_timeslots') %}
          {% set p_deferrable1_hours = states('sensor.p_deferrable1_hours') %}
          {% if active_timeslots == 'unavailable' or p_deferrable1_hours == 'unavailable' %}
            0
          {% else %}
            {% set active_timeslots = active_timeslots | int %}
            {% set p_deferrable1_hours = p_deferrable1_hours | int %}
            {% if p_deferrable1_hours == 0 %}
              0
            {% else %}
              {{ active_timeslots - p_deferrable1_hours }}
            {% endif %}
          {% endif %}

      active_timeslots_minus_deferrable3_hours:
        friendly_name: "Active Tslots Minus Def3 Hours"
        unit_of_measurement: "hours"
        value_template: >
          {% set active_timeslots = states('sensor.active_timeslots') %}
          {% set p_deferrable3_hours = states('sensor.p_deferrable3_hours') %}
          {% if active_timeslots == 'unavailable' or p_deferrable3_hours == 'unavailable' %}
            0
          {% else %}
            {% set active_timeslots = active_timeslots | int %}
            {% set p_deferrable3_hours = p_deferrable3_hours | int %}
            {% if p_deferrable3_hours == 0 %}
              0
            {% else %}
              {{ active_timeslots - p_deferrable3_hours }}
            {% endif %}
          {% endif %}

# Def 0 Tvättmaskin sensor.tvattmaskin_energy_power
# Def 1 Diskmaskin sensor.nous_1_energy_power
# Def 2 Laddboxen sensor.laddboxforbrukning_power
# Def 3 Torktumlaren sensor.torktumlare_energy_power
