################################################################################
#                Detta är till för elpriserna                                  #
################################################################################
sensor:
  - platform: rest
    name: Tibber prices
    resource: https://api.tibber.com/v1-beta/gql
    method: POST
    scan_interval: 60
    payload: '{ "query": "{ viewer { homes { currentSubscription { priceInfo { today { total startsAt } tomorrow { total startsAt }}}}}}" }'
    json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
    json_attributes:
      - today
      - tomorrow
    value_template: Ok
    headers:
      Authorization: "228d305b78a81fcd5441995a20a5160c599f49b29e0b806154d5a66e86e49e1c"
      Content-Type: application/json
      User-Agent: REST

template:
  - sensor:
      - name: "Peak elpris"
        unique_id: peak_el_pris
        unit_of_measurement: "Sek/kWh"
        state: "{{ state_attr('sensor.nordpool_kwh_se3_sek_3_10_025', 'peak') }}"

      - name: "Offpeak elpris"
        unique_id: offpeak_el_pris
        unit_of_measurement: "Sek/kWh"
        state: "{{ state_attr('sensor.nordpool_kwh_se3_sek_3_10_025', 'off_peak_1') }}"

      - name: "Text elpris"
        unique_id: text_el_pris
        state: "{{ state_attr('sensor.electricity_price_goktytan_4', 'price_level') }}"

      - name: "Tibber Totalpris"
        unique_id: tibber_total_price
        unit_of_measurement: "Sek/kWh"
        state: >-
          {{ states('sensor.nordpool_kwh_se3_sek_3_10_025') | float + 0.09 + 
          ((49 / (now().replace(day=1, month=now().month % 12 + 1) - timedelta(days=1)).day) / 24) }}
################################################################################
##  END
################################################################################
