################################################################################
## EMHASS CONFIG by Johan71
################################################################################
# Do not remove; consider potential consequences.
sensor:
  - platform: template
    sensors:
      power_load_novar_loads:
        friendly_name: "Power load novar loads"
        unit_of_measurement: "W"
        device_class: "power"
        unique_id: ab0230e2-2e23-40d0-ac97-d5ddb74707ca
        value_template: >
          {% set powerload = states('sensor.house_consumption_power') | float(default=0) %}
          {% set laddbox_power = states('sensor.go_echarger_265216_nrg_12') | float(default=0) %}
          {% set value = (powerload - laddbox_power) | round(1) %}
          {{ value }}

################################################################################
## Fifobuffer CONFIG by Johan71
################################################################################

  - platform: filter
    name: "1_minute_average"
    entity_id: sensor.power_load_novar_loads
    filters:
      - filter: time_simple_moving_average
        window_size: "00:01"  # Beräknar medelvärdet över varje minut
        precision: 2

  - platform: filter
    name: "30_minute_average"
    entity_id: sensor.1_minute_average
    filters:
      - filter: time_simple_moving_average
        window_size: "00:30"  # Beräknar medel över 30 minuter
        precision: 2
        
#### Carcharger sensors#########################################################

  # Percentage of charge we can add to a max of 90%, based on the Volvo integration
  - platform: template
    sensors:
      c40_additional_charge_percentage:
        unit_of_measurement: "%"
        device_class: power_factor
        value_template: >
          {% set current_charge = states('sensor.volvo_yv1xkefv1p2046163_battery_charge_level') | int(0) %}
          {% set max_charge = states('input_number.c40_max_charge_percentage') | int(90) %}
          {% if current_charge >= max_charge %}
            {{ 0 }}
          {% else %}
            {{ (max_charge - current_charge) }}
          {% endif %}

  # Multiplied by battery capacity 67 kWh
  - platform: template
    sensors:
      c40_additional_charge_kwh:
        unit_of_measurement: "kWh"
        device_class: energy
        value_template: >
          {{ 67 * (states('sensor.c40_additional_charge_percentage') | int) / 100 }}

  # Charging with a max of 6 kWh
  - platform: template
    sensors:
      c40_additional_charge_hours:
        unit_of_measurement: "h"
        device_class: duration
        value_template: >
          {{ ((states('sensor.c40_additional_charge_kwh') | float) / 6.0) | round(0, "ceil", 0) }}

  # Check the Easee charger if the car is connected, otherwise the number of hours is 0
  - platform: template
    sensors:
      c40_additional_charge_hours_if_connected:
        unit_of_measurement: "h"
        device_class: duration
        value_template: >
          {{ (states('sensor.c40_additional_charge_hours') | int if states('binary_sensor.go_echarger_265216_car') in ("on", "ready_to_charge", "charging") else 0) }}

  # Calculate additional charge in watts
  - platform: template
    sensors:
      c40_additional_charge_watts:
        unit_of_measurement: "W"
        device_class: power
        value_template: >
          {{ min(6700, ((states('sensor.c40_additional_charge_kwh') | float) / 6.0) * 6700) | round(0, "ceil", 0) }}

  # Hours until next 08:00
  - platform: template
    sensors:
      hours_until_next_0800:
        friendly_name: "Hours Until Next 08:00"
        unit_of_measurement: "h"
        device_class: duration
        value_template: >
          {% if now().hour >= 8 %}
            {{ (24 - now().hour + 7) + (0 if now().minute > 30 else 1) }}
          {% else %}
            {{ (8 - now().hour) + (0 if now().minute > 30 else 1) }}
          {% endif %}
          
input_number:
  c40_max_charge_percentage:
    name: "Max Charge Percentage"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:battery-charging

################################################################################
# END
################################################################################
